// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GitWorkTree
{
    internal sealed partial class Vsix
    {
        public const string Id = "GitWorktree.bcf469f6-35d7-4aa1-8556-6e22d0309d94";
        public const string Name = "GitWorktree";
        public const string Description = @"Enhance your Visual Studio 2022 workflow with Git Worktree. Simplify the management of parallel workstreams without the hassle of typing Git Worktree commands.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Senthil V";
        public const string Tags = "";
    }
}
