// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GitWorkTree
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidGitWorkTreePackageString = "f5cfcdcd-f0ac-4140-bd08-4b122f188161";
        public static Guid guidGitWorkTreePackage = new Guid(guidGitWorkTreePackageString);

        public const string guidGitWorkTreePackageCmdSetString = "22cfbf67-12c4-4ab9-9ce7-99e7bd912228";
        public static Guid guidGitWorkTreePackageCmdSet = new Guid(guidGitWorkTreePackageCmdSetString);

        public const string PackageCommandSetGuidString = "57735d06-c920-4415-a2e0-7d6e6fbdfa99";
        public static Guid PackageCommandSetGuid = new Guid(PackageCommandSetGuidString);

        public const string guidGitWorkTreeOutpaneString = "975c7015-667e-4e4b-9bba-b02951d4fac4";
        public static Guid guidGitWorkTreeOutpane = new Guid(guidGitWorkTreeOutpaneString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int GitWorkTreeMenu = 0x0001;
        public const int SubMenu = 0x0002;
        public const int SubMenuGroup = 0x0003;
        public const int CreateWorkTreeCommand = 0x0100;
        public const int ManageWorkTreesCommand = 0x0200;
        public const int GitRootMenu = 0xF000;
    }
}